#!/usr/bin/env python3
"""Inspect an X-HD ACM supplement zip and emit normalized intake JSON.

This app-owned helper is for a future ACM-access reviewer or owner who has
obtained ``ics26-106.zip``. It records a conservative file listing and classifies
whether the zip appears to contain artifact material. It does not claim that the
supplement was inspected unless run on a concrete local zip supplied by the
caller.
"""

from __future__ import annotations

import argparse
import datetime as _dt
import hashlib
import json
import pathlib
import sys
import zipfile
from typing import Any, Dict, Iterable, List


DATASET_SUFFIXES = (
    ".ply",
    ".off",
    ".wkt",
    ".nii",
    ".nii.gz",
    ".csv",
    ".tsv",
    ".parquet",
    ".jsonl",
)
ARCHIVE_SUFFIXES = (".zip", ".tar", ".tgz", ".tar.gz", ".tar.zst", ".7z", ".bz2", ".gz")
HASH_TOKENS = ("sha256", "sha-256", "checksum", "checksums", "hash", "manifest", "md5")
DATASET_TOKENS = ("hddatasets", "dataset", "datasets", "input", "inputs", "dragon", "buddha", "brats", "water", "zipcode", "county")
SCRIPT_SUFFIXES = (".sh", ".py", ".ps1", ".bat", ".cu", ".cpp", ".cmake")
SCRIPT_TOKENS = ("readme", "artifact", "reproduce", "regenerate", "download", "prepare", "run_", "script", "instructions")


def _sha256_file(path: pathlib.Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def _top_level(paths: Iterable[str]) -> List[str]:
    seen = set()
    out: List[str] = []
    for p in paths:
        clean = p.strip("/")
        if not clean:
            continue
        first = clean.split("/", 1)[0]
        if first not in seen:
            seen.add(first)
            out.append(first)
    return out


def _is_dataset_or_hash(path: str) -> bool:
    lower = path.lower()
    return (
        lower.endswith(DATASET_SUFFIXES)
        or lower.endswith(ARCHIVE_SUFFIXES)
        or any(token in lower for token in HASH_TOKENS)
        or any(token in lower for token in DATASET_TOKENS)
    )


def _is_script_or_instruction(path: str) -> bool:
    lower = path.lower()
    return lower.endswith(SCRIPT_SUFFIXES) or any(token in lower for token in SCRIPT_TOKENS)


def inspect_zip(
    zip_path: pathlib.Path,
    reviewer_name: str,
    contact_or_source: str,
    received_date: str | None = None,
) -> Dict[str, Any]:
    zip_path = zip_path.resolve()
    if received_date is None:
        received_date = _dt.date.today().isoformat()
    if not zipfile.is_zipfile(zip_path):
        raise ValueError(f"not a zip file: {zip_path}")

    with zipfile.ZipFile(zip_path) as zf:
        names = [info.filename for info in zf.infolist() if not info.is_dir()]

    dataset_or_hash_entries = sorted([name for name in names if _is_dataset_or_hash(name)])
    script_or_instruction_entries = sorted([name for name in names if _is_script_or_instruction(name)])
    contains_artifact = bool(dataset_or_hash_entries or script_or_instruction_entries)

    return {
        "schema": "rtdl.paper_reproduction.xhd.external_response_intake.v1",
        "status": "filled_from_acm_supplement_inspector",
        "received_from": {
            "actor_type": "acm_access_reviewer",
            "name_or_role": reviewer_name,
            "contact_or_source": contact_or_source,
            "received_date": received_date,
        },
        "response_type": "acm_supplement_artifact_instructions",
        "scope": {
            "paper": "X-HD",
            "families": [],
            "paper_paths_or_figures": [],
            "claim_boundary_requested": "unknown",
        },
        "artifacts": {
            "hash_manifest_entries": [],
            "archive": None,
            "regeneration_script": None,
            "acm_supplement_listing": {
                "zip_filename": zip_path.name,
                "zip_sha256": _sha256_file(zip_path),
                "total_files": len(names),
                "top_level_files": _top_level(names),
                "all_files": names,
                "contains_artifact_material": contains_artifact,
                "dataset_or_hash_entries": dataset_or_hash_entries,
                "script_or_instruction_entries": script_or_instruction_entries,
            },
            "exact_equivalence_verdict": None,
            "freeform_notes": "Generated by inspect_xhd_acm_supplement_zip.py from a local zip file. Heuristic classification requires review before any claim.",
        },
        "validation_status": {
            "validated_by_codex": False,
            "sufficient_to_run_pod_gate": False,
            "sufficient_to_claim_exact_input": False,
            "requires_external_review_before_use": True,
            "failure_or_missing_items": [],
        },
        "next_action": "classify_response_before_action",
        "claim_boundary": {
            "request_sent_claimed": False,
            "external_response_received": False,
            "external_artifacts_acquired": False,
            "acm_supplement_inspected": False,
            "exact_equivalence_accepted": False,
            "exact_paper_dataset_reproduction_claimed": False,
            "figure5_reproduction_claimed": False,
            "full_paper_reproduction_claimed": False,
            "performance_ratio_claimed": False,
        },
    }


def main(argv: List[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("zip_path", type=pathlib.Path)
    parser.add_argument("--reviewer-name", default="local ACM-access reviewer")
    parser.add_argument("--contact-or-source", default="local inspection")
    parser.add_argument("--received-date", default=None)
    parser.add_argument("--output", type=pathlib.Path, default=None)
    args = parser.parse_args(argv)

    try:
        payload = inspect_zip(args.zip_path, args.reviewer_name, args.contact_or_source, args.received_date)
    except Exception as exc:
        print(f"inspection failed: {exc}", file=sys.stderr)
        return 2

    text = json.dumps(payload, indent=2, sort_keys=True)
    if args.output:
        args.output.write_text(text + "\n", encoding="utf-8")
    else:
        print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
