from __future__ import annotations

import argparse
import json
import re
import statistics
from pathlib import Path
from typing import Sequence


REVENUE_PATTERN = re.compile(r"^Revenue: ([0-9]+)$", re.MULTILINE)
TOTAL_PATTERN = re.compile(r"^Time Taken Total: ([0-9.eE+-]+)$", re.MULTILINE)
QUERY_PATTERN = re.compile(r'^\{"query":11,"time_query":([0-9.eE+-]+)\}$', re.MULTILINE)


def _load(path: Path) -> dict[str, object]:
    return json.loads(path.read_text(encoding="utf-8"))


def parse_crystal_q11(raw_stdout: str) -> dict[str, object]:
    revenues = [int(value) for value in REVENUE_PATTERN.findall(raw_stdout)]
    total_ms = [float(value) for value in TOTAL_PATTERN.findall(raw_stdout)]
    query_ms = [float(value) for value in QUERY_PATTERN.findall(raw_stdout)]
    if not revenues or len(revenues) != len(total_ms) or len(revenues) != len(query_ms):
        raise ValueError("Crystal q11 output must contain matching revenue, total, and query records")
    if len(set(revenues)) != 1:
        raise ValueError("Crystal q11 trials disagree on revenue")
    return {
        "trial_count": len(revenues),
        "revenues": revenues,
        "revenue": revenues[0],
        "time_query_ms": query_ms,
        "time_query_median_ms": statistics.median(query_ms),
        "time_total_ms": total_ms,
        "time_total_median_ms": statistics.median(total_ms),
    }


def build_gate(
    packet: dict[str, object],
    author: dict[str, object],
    rtdl: dict[str, object],
    crystal: dict[str, object],
    *,
    crystal_binary_sha256: str,
    crystal_q11_source_sha256: str,
) -> dict[str, object]:
    if int(packet["row_count"]) != 6_001_171:
        raise ValueError("the first Crystal gate requires upstream Crystal SF1 row count 6,001,171")
    for field in ("data_sha256", "predicate_sha256", "expected_rows_sha256"):
        if packet[field] != author[field] or packet[field] != rtdl[field]:
            raise ValueError(f"RayDB/RTDL packet identity mismatch: {field}")
    expected_rows = packet["expected_rows"]
    if author.get("author_rows") != expected_rows or rtdl.get("rtdl_rows") != expected_rows:
        raise ValueError("RayDB or RTDL differs from the independent packet oracle")
    if not bool(author.get("author_matches_cpu_oracle")):
        raise ValueError("author correctness gate did not pass")
    if not bool(rtdl.get("rtdl_matches_oracle")) or not bool(rtdl.get("author_matches_rtdl")):
        raise ValueError("RTDL correctness gate did not pass")
    if len(expected_rows) != 1 or expected_rows[0]["group"] != [0]:
        raise ValueError("Crystal q11 gate requires one scalar group")
    expected_revenue = int(expected_rows[0]["value"])
    if int(crystal["revenue"]) != expected_revenue:
        raise ValueError("upstream Crystal q11 revenue differs from the independent oracle")

    return {
        "schema": "rtdl.paper_reproduction.raydb.crystal_q11_same_source_gate.v1",
        "host": "lx1",
        "gpu": "NVIDIA GeForce GTX 1070",
        "workload": "SSB SF1 q11 generated by upstream Crystal bundled dbgen",
        "source_provenance": {
            "crystal_repository": "https://github.com/anilshanbhag/crystal",
            "crystal_commit": "f2179e607eb923f2053a706c1e30aa2b6161b9db",
            "crystal_cub_version": "1.6.4",
            "raw_lineorder_sha256": packet["lineorder_sha256"],
            "raw_lineorder_rows": int(packet["row_count"]),
            "crystal_binary_sha256": crystal_binary_sha256,
            "crystal_q11_source_sha256": crystal_q11_source_sha256,
            "raydb_author_binary_sha256": author["author_binary_sha256"],
            "same_raw_lineorder_source_for_crystal_and_packet_builder": True,
            "same_binary_packet_bytes_for_raydb_and_rtdl": True,
            "paper_modified_crystal_source_available": False,
            "exact_paper_input_claimed": False,
        },
        "correctness": {
            "expected_revenue": expected_revenue,
            "crystal_revenue": int(crystal["revenue"]),
            "raydb_author_rows": author["author_rows"],
            "rtdl_rows": rtdl["rtdl_rows"],
            "crystal_matches_oracle": True,
            "raydb_author_matches_oracle": True,
            "rtdl_matches_oracle": True,
            "all_three_match": True,
        },
        "timing_diagnostics": {
            "crystal_upstream_q11": crystal,
            "author_internal_lines": [
                line for line in str(author["raw_stdout"]).splitlines() if line.startswith("[Time]")
            ],
            "rtdl_phase_timing_seconds": rtdl["phase_timing_seconds"],
            "ratio_authorized": False,
            "reason": (
                "upstream Crystal is not the paper-modified baseline and Crystal, RayDB, and RTDL "
                "timers cover different setup, launch, and result-download boundaries"
            ),
        },
        "decision": {
            "same_source_q11_correctness_gate": "passed",
            "upstream_crystal_baseline_feasible_on_current_host": True,
            "figure12_crystal_baseline_reproduced": False,
            "performance_ratio_authorized": False,
            "next_action": (
                "retain q11 as a feasibility anchor; recover or reconstruct the disclosed paper "
                "Crystal modifications and align phase instrumentation before performance comparison"
            ),
        },
        "claim_boundary": {
            "q11_same_source_scalar_correctness_claimed": True,
            "all_13_crystal_queries_claimed": False,
            "paper_modified_crystal_reproduced": False,
            "figure12_reproduced": False,
            "paper_performance_claimed": False,
            "cross_implementation_ratio_claimed": False,
            "full_paper_reproduction_claimed": False,
        },
    }


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build the same-source Crystal/RayDB/RTDL q11 gate")
    parser.add_argument("--packet", type=Path, required=True)
    parser.add_argument("--author", type=Path, required=True)
    parser.add_argument("--rtdl", type=Path, required=True)
    parser.add_argument("--crystal-stdout", type=Path, required=True)
    parser.add_argument("--crystal-binary-sha256", required=True)
    parser.add_argument("--crystal-q11-source-sha256", required=True)
    parser.add_argument("--output-json", type=Path, required=True)
    args = parser.parse_args(argv)
    result = build_gate(
        _load(args.packet),
        _load(args.author),
        _load(args.rtdl),
        parse_crystal_q11(args.crystal_stdout.read_text(encoding="utf-8")),
        crystal_binary_sha256=args.crystal_binary_sha256,
        crystal_q11_source_sha256=args.crystal_q11_source_sha256,
    )
    args.output_json.parent.mkdir(parents=True, exist_ok=True)
    args.output_json.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(result["decision"], indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
