#!/usr/bin/env bash
set -euo pipefail

# Goal5057 POD environment bootstrap for v2.14.4 CUDA/Numba runtime smokes.
# Boundary: environment setup + runtime self-test only; no performance claims.

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT}"

OUTPUT_JSON="${1:-history/internal_docs/goal5057_v2144_pod_env_bootstrap_result.json}"
EXPORTS_SH="${RTDL_V2144_POD_ENV_EXPORTS:-history/internal_docs/goal5057_v2144_pod_env_exports.sh}"

VENV="${RTDL_V2144_POD_VENV:-.venv_v2144_pod}"
BOOTSTRAP_PYTHON="${RTDL_V2144_BOOTSTRAP_PYTHON:-python3}"
NUMPY_VERSION="${RTDL_V2144_NUMPY_VERSION:-2.2.6}"
NUMBA_VERSION="${RTDL_V2144_NUMBA_VERSION:-0.61.2}"
CUDA_NVCC_VERSION="${RTDL_V2144_CUDA_NVCC_VERSION:-12.4.131}"
CUDA_NVRTC_VERSION="${RTDL_V2144_CUDA_NVRTC_VERSION:-12.4.127}"
NVJITLINK_VERSION="${RTDL_V2144_NVJITLINK_VERSION:-12.4.127}"

mkdir -p "$(dirname "${OUTPUT_JSON}")" "$(dirname "${EXPORTS_SH}")"

if [ ! -x "${VENV}/bin/python" ]; then
  "${BOOTSTRAP_PYTHON}" -m venv "${VENV}"
fi

"${VENV}/bin/python" -m pip install --upgrade pip
"${VENV}/bin/python" -m pip install \
  "numpy==${NUMPY_VERSION}" \
  "numba==${NUMBA_VERSION}" \
  "nvidia-cuda-nvcc-cu12==${CUDA_NVCC_VERSION}" \
  "nvidia-cuda-nvrtc-cu12==${CUDA_NVRTC_VERSION}" \
  "nvidia-nvjitlink-cu12==${NVJITLINK_VERSION}"

CUDA_HOME="$("${VENV}/bin/python" - <<'PY'
from pathlib import Path
import site
for base in site.getsitepackages():
    candidate = Path(base) / "nvidia" / "cuda_nvcc"
    if (candidate / "nvvm" / "lib64").is_dir() and (candidate / "nvvm" / "libdevice").is_dir():
        print(candidate)
        raise SystemExit(0)
raise SystemExit("could not locate nvidia/cuda_nvcc inside the POD venv")
PY
)"

cat > "${EXPORTS_SH}" <<EOF
# Generated by scripts/goal5057_v2144_pod_env_bootstrap.sh
export RTDL_V2144_POD_VENV='${ROOT}/${VENV}'
export CUDA_HOME='${CUDA_HOME}'
export CUDA_PATH='${CUDA_HOME}'
export LD_LIBRARY_PATH='${CUDA_HOME}/nvvm/lib64':"\${LD_LIBRARY_PATH:-}"
export PATH='${ROOT}/${VENV}/bin':'${CUDA_HOME}/bin':"\${PATH}"
EOF

set +u
# shellcheck disable=SC1090
source "${EXPORTS_SH}"
set -u

"${VENV}/bin/python" - "${OUTPUT_JSON}" "${CUDA_HOME}" "${VENV}" <<'PY'
from __future__ import annotations

import json
import os
from pathlib import Path
import subprocess
import sys
import time


output = Path(sys.argv[1])
cuda_home = Path(sys.argv[2])
venv = Path(sys.argv[3])
started = time.perf_counter()

payload: dict[str, object] = {
    "schema": "rtdl.goal5057.v2_14_4_pod_env_bootstrap.v1",
    "overall_status": "fail",
    "venv": str(venv),
    "cuda_home": str(cuda_home),
    "not_authorized": {
        "public_release_ready": True,
        "v2_14_4_speedup_claim": True,
        "true_zero_copy_claim": True,
        "author_parity_claim": True,
        "device_group_by_public_ready": True,
    },
}

try:
    import numpy as np
    import numba
    from numba import cuda
    from numba.cuda.cudadrv import libs

    nvvm = str(libs.get_cudalib("nvvm"))
    libdevice = str(libs.get_libdevice())
    ptxas = subprocess.run(
        ["ptxas", "--version"],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    ).stdout.strip()

    @cuda.jit
    def _goal5057_increment(values):
        idx = cuda.grid(1)
        if idx < values.size:
            values[idx] += 1

    values = cuda.to_device(np.asarray([1], dtype=np.int32))
    _goal5057_increment[1, 1](values)
    cuda.synchronize()
    observed = values.copy_to_host().astype(np.int32).tolist()
    if observed != [2]:
        raise AssertionError(f"unexpected CUDA kernel result {observed}")

    device = cuda.get_current_device()
    payload.update(
        {
            "overall_status": "pass",
            "elapsed_sec": time.perf_counter() - started,
            "python_executable": sys.executable,
            "python_version": sys.version,
            "numpy_version": np.__version__,
            "numba_version": numba.__version__,
            "cuda_available": bool(cuda.is_available()),
            "cuda_device_name": device.name.decode() if isinstance(device.name, bytes) else str(device.name),
            "cuda_compute_capability": list(device.compute_capability),
            "nvvm": nvvm,
            "libdevice": libdevice,
            "ptxas_version": ptxas,
            "minimal_cuda_kernel_result": observed,
        }
    )
except Exception as exc:
    payload.update(
        {
            "overall_status": "fail",
            "elapsed_sec": time.perf_counter() - started,
            "error": f"{type(exc).__name__}: {exc}",
        }
    )

output.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
print(json.dumps(payload, indent=2, sort_keys=True))
raise SystemExit(0 if payload["overall_status"] == "pass" else 1)
PY

echo "Goal5057 POD env bootstrap complete: ${OUTPUT_JSON}"
echo "Goal5057 exports: ${EXPORTS_SH}"
