from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
from pathlib import Path
from typing import Any

from scripts.goal2201_rayjoin_same_query_evidence_report import MODES
from scripts.goal2201_rayjoin_same_query_evidence_report import WORKLOADS
from scripts.goal2201_rayjoin_same_query_evidence_report import build_summary
from scripts.goal2201_rayjoin_same_query_evidence_report import render_markdown


ROOT = Path(__file__).resolve().parents[1]
BLOCKED_CLAIM_KEYS = (
    "paper_scale_perf_claim_authorized",
    "rtdl_beats_rayjoin_claim_authorized",
    "broad_rt_core_speedup_claim_authorized",
    "v2_0_release_authorized",
)


def _resolve(path: str | Path) -> Path:
    value = Path(path)
    if value.is_absolute():
        return value
    return ROOT / value


def _git_commit() -> str:
    try:
        return subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=ROOT,
            check=True,
            text=True,
            capture_output=True,
        ).stdout.strip()
    except Exception:
        return "unknown"


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _copy_required(src: Path, dst_dir: Path) -> dict[str, Any]:
    if not src.exists():
        raise FileNotFoundError(f"missing required pod artifact: {src}")
    dst = dst_dir / src.name
    shutil.copy2(src, dst)
    return {
        "name": src.name,
        "source": str(src),
        "imported": str(dst),
        "bytes": dst.stat().st_size,
        "sha256": _sha256(dst),
    }


def _stream_path(artifact_dir: Path, workload: str, summary: dict[str, Any]) -> Path:
    query_count = int(summary["rtdl"][workload]["query_count"])
    return artifact_dir / f"rayjoin_{workload}_gen{query_count}_stream.json"


def _validate_boundaries(summary: dict[str, Any]) -> None:
    boundary = summary.get("claim_boundary", {})
    if not boundary.get("same_contract_with_rayjoin_query_exec"):
        raise ValueError("summary does not mark same_contract_with_rayjoin_query_exec=true")
    for key in BLOCKED_CLAIM_KEYS:
        if boundary.get(key):
            raise ValueError(f"blocked claim key unexpectedly true: {key}")


def import_artifacts(
    *,
    artifact_dir: Path,
    output_dir: Path,
    output_json: Path,
    output_md: Path,
    include_streams: bool,
) -> dict[str, Any]:
    artifact_dir = _resolve(artifact_dir)
    output_dir = _resolve(output_dir)
    output_json = _resolve(output_json)
    output_md = _resolve(output_md)
    output_dir.mkdir(parents=True, exist_ok=True)
    output_json.parent.mkdir(parents=True, exist_ok=True)
    output_md.parent.mkdir(parents=True, exist_ok=True)

    summary = build_summary(artifact_dir)
    _validate_boundaries(summary)

    imported_files: list[dict[str, Any]] = []
    for name in ("environment.txt", "progress.log", "summary.json"):
        imported_files.append(_copy_required(artifact_dir / name, output_dir))
    for workload in WORKLOADS:
        for mode in MODES:
            imported_files.append(_copy_required(artifact_dir / f"rayjoin_{workload}_{mode}.log", output_dir))
        imported_files.append(_copy_required(artifact_dir / f"rtdl_{workload}_same_rayjoin_stream.json", output_dir))

    stream_provenance = []
    for workload in WORKLOADS:
        stream = _stream_path(artifact_dir, workload, summary)
        if not stream.exists():
            raise FileNotFoundError(f"missing required RayJoin query stream for hashing: {stream}")
        item = {
            "workload": workload,
            "name": stream.name,
            "source": str(stream),
            "bytes": stream.stat().st_size,
            "sha256": _sha256(stream),
            "copied_into_repo": bool(include_streams),
        }
        if include_streams:
            dst = output_dir / stream.name
            shutil.copy2(stream, dst)
            item["imported"] = str(dst)
        stream_provenance.append(item)

    regenerated_summary_path = output_dir / "evidence_summary.regenerated.json"
    regenerated_report_path = output_dir / "evidence_report.regenerated.md"
    regenerated_summary_path.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    regenerated_report_path.write_text(render_markdown(summary), encoding="utf-8")
    imported_files.append(
        {
            "name": regenerated_summary_path.name,
            "source": "generated by Goal2204 importer from imported raw artifacts",
            "imported": str(regenerated_summary_path),
            "bytes": regenerated_summary_path.stat().st_size,
            "sha256": _sha256(regenerated_summary_path),
        }
    )
    imported_files.append(
        {
            "name": regenerated_report_path.name,
            "source": "generated by Goal2204 importer from imported raw artifacts",
            "imported": str(regenerated_report_path),
            "bytes": regenerated_report_path.stat().st_size,
            "sha256": _sha256(regenerated_report_path),
        }
    )

    import_summary = {
        "goal": "2204",
        "status": "imported",
        "source_artifact_dir": str(artifact_dir),
        "output_dir": str(output_dir),
        "rtdl_commit": _git_commit(),
        "include_streams": bool(include_streams),
        "imported_files": imported_files,
        "stream_provenance": stream_provenance,
        "evidence_summary": summary,
        "claim_boundary": {
            "same_contract_with_rayjoin_query_exec": True,
            "paper_scale_perf_claim_authorized": False,
            "rtdl_beats_rayjoin_claim_authorized": False,
            "broad_rt_core_speedup_claim_authorized": False,
            "v2_0_release_authorized": False,
        },
    }
    output_json.write_text(json.dumps(import_summary, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    output_md.write_text(render_import_markdown(import_summary), encoding="utf-8")
    return import_summary


def render_import_markdown(import_summary: dict[str, Any]) -> str:
    summary = import_summary["evidence_summary"]
    lines = [
        "# Goal2204 RayJoin Same-Query Pod Artifact Import",
        "",
        "Status: imported pod artifacts for review; public performance claims remain unauthorized.",
        "",
        "## Import",
        "",
        f"- Source artifact directory: `{import_summary['source_artifact_dir']}`",
        f"- Repo artifact directory: `{import_summary['output_dir']}`",
        f"- Full query streams copied into repo: `{str(import_summary['include_streams']).lower()}`",
        "",
        "## Stream Provenance",
        "",
        "| Workload | Stream | Bytes | SHA-256 | Copied |",
        "| --- | --- | ---: | --- | --- |",
    ]
    for item in import_summary["stream_provenance"]:
        lines.append(
            f"| `{item['workload']}` | `{item['name']}` | {item['bytes']} | "
            f"`{item['sha256']}` | {str(item['copied_into_repo']).lower()} |"
        )

    lines.extend(
        [
            "",
            "## Imported Files",
            "",
            "| File | Bytes | SHA-256 |",
            "| --- | ---: | --- |",
        ]
    )
    for item in import_summary["imported_files"]:
        lines.append(f"| `{item['name']}` | {item['bytes']} | `{item['sha256']}` |")

    lines.extend(
        [
            "",
            "## Evidence Summary",
            "",
            render_markdown(summary),
            "",
            "## Boundary",
            "",
            "This import does not authorize RayJoin paper reproduction, RTDL beating RayJoin, broad RT-core speedup, or v2.0 release readiness.",
            "Those claims require external review and a separate consensus report over the imported artifacts.",
            "",
        ]
    )
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Import Goal2198 RayJoin same-query pod artifacts into docs/reports.")
    parser.add_argument("--artifact-dir", required=True)
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--output-json", required=True)
    parser.add_argument("--output-md", required=True)
    parser.add_argument("--include-streams", action="store_true")
    args = parser.parse_args(argv)

    import_artifacts(
        artifact_dir=Path(args.artifact_dir),
        output_dir=Path(args.output_dir),
        output_json=Path(args.output_json),
        output_md=Path(args.output_md),
        include_streams=bool(args.include_streams),
    )
    print(f"[goal2204] imported {args.artifact_dir} -> {args.output_dir}")
    print(f"[goal2204] wrote {args.output_json}")
    print(f"[goal2204] wrote {args.output_md}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
