"""Narrow public research API for RTDL V4 restricted Python callbacks.

The public surface deliberately stops at verified Callback IR and the audited
compiler building blocks.  User source is parsed as text and is never imported
or executed by Python.  Native materialization remains an explicit, target-
bound operation; this module does not expose an arbitrary PTX/provider escape
hatch.
"""

from __future__ import annotations

from .v4_callback_abi import (
    AnyHitProofAuthority,
    CallbackAbiError,
    CompiledCallbackAbi,
    compile_callback_abi,
    derive_compiler_recognized_any_hit_proof,
)
from .v4_callback_frontend import compile_callback_source, parse_callback_source
from .v4_callback_interpreter import (
    CallbackExecutionResult,
    CallbackRuntimeError,
    RuntimeEffect,
    RuntimeRecord,
    execute_callback_role,
)
from .v4_callback_ir import (
    AABB3F,
    BOOL,
    F32,
    F64,
    HIT,
    I32,
    I64,
    RAY3F,
    TRIANGLE_HIT,
    U32,
    U64,
    AnyHitDeliveryContract,
    CallbackModuleManifest,
    CallbackProgramSpec,
    CallbackRole,
    CallbackVerificationError,
    FrozenConstant,
    GeometryAdmission,
    GeometryContract,
    GeometryProofAuthority,
    LinkageMechanism,
    NumericContract,
    ResourceBudget,
    RuntimeStatus,
    VerifiedCallbackProgram,
)
from .v4_callback_lifecycle import (
    AnyHitProtocolProof,
    BoundedRelationBatch,
    BoundedRelationProtocol,
    BoundedRelationStaticInput,
    MaterializedProtocolProgram,
    PreparedProtocolProgram,
    ProtocolExecutableIdentity,
    ProtocolExecutionResult,
    ProtocolFamily,
    ProtocolLifecycleError,
    ProtocolPhysicalPlan,
    ProtocolProgramIdentity,
    TriangleReductionBatch,
    TriangleReductionMode,
    TriangleReductionProtocol,
    TriangleReductionStaticInput,
    V4Target,
    V4Toolchain,
    VerifiedProtocolProgram,
    compile_protocol_program,
    materialize_protocol_program,
    standard_protocol_physical_plan,
)
from .v4_protocol_contract import (
    CompilerProtocolProjection,
    ProtocolContractDecision,
    ProtocolContractDeclaration,
    ProtocolContractError,
    ProtocolContractFinding,
    ProtocolMechanism,
    verify_protocol_contract,
)
from .v4_public_builtin_triangle import (
    BuiltinTriangleCallbackBatch,
    BuiltinTriangleCallbackExecutableIdentity,
    BuiltinTriangleCallbackExecutionResult,
    BuiltinTriangleCallbackPhysicalPlan,
    BuiltinTriangleCallbackProgramIdentity,
    BuiltinTriangleCallbackStaticInput,
    BuiltinTriangleOrientationDeclaration,
    BuiltinTriangleU32x3FieldIds,
    MaterializedBuiltinTriangleCallbackProgram,
    PreparedBuiltinTriangleCallbackProgram,
    PublicCallbackLifecycleError,
    VerifiedBuiltinTriangleCallbackProgram,
    VerifiedBuiltinTriangleCallbackSource,
    compile_builtin_triangle_callback_program,
    build_builtin_triangle_u32x3_physical_plan,
    materialize_builtin_triangle_callback_program,
    verify_builtin_triangle_callback_source,
)
from .v4_typed_physical_schema import (
    BUILTIN_TRIANGLE_CONTRACT,
    AdjacencySide,
    PhysicalSchemaError,
    TriangleWindingPolicy,
)


V4_API_VERSION = "4.0.0rc1"


__all__ = sorted([
    "AABB3F",
    "BOOL",
    "F32",
    "F64",
    "HIT",
    "I32",
    "I64",
    "RAY3F",
    "TRIANGLE_HIT",
    "U32",
    "U64",
    "AnyHitDeliveryContract",
    "AnyHitProofAuthority",
    "AnyHitProtocolProof",
    "AdjacencySide",
    "BUILTIN_TRIANGLE_CONTRACT",
    "BoundedRelationBatch",
    "BoundedRelationProtocol",
    "BoundedRelationStaticInput",
    "BuiltinTriangleCallbackBatch",
    "BuiltinTriangleCallbackExecutableIdentity",
    "BuiltinTriangleCallbackExecutionResult",
    "BuiltinTriangleCallbackPhysicalPlan",
    "BuiltinTriangleCallbackProgramIdentity",
    "BuiltinTriangleCallbackStaticInput",
    "BuiltinTriangleOrientationDeclaration",
    "BuiltinTriangleU32x3FieldIds",
    "CallbackAbiError",
    "CallbackExecutionResult",
    "CallbackModuleManifest",
    "CallbackProgramSpec",
    "CallbackRole",
    "CallbackRuntimeError",
    "CallbackVerificationError",
    "CompiledCallbackAbi",
    "CompilerProtocolProjection",
    "FrozenConstant",
    "GeometryAdmission",
    "GeometryContract",
    "GeometryProofAuthority",
    "LinkageMechanism",
    "MaterializedBuiltinTriangleCallbackProgram",
    "NumericContract",
    "MaterializedProtocolProgram",
    "ProtocolContractDecision",
    "ProtocolContractDeclaration",
    "ProtocolContractError",
    "ProtocolContractFinding",
    "PreparedProtocolProgram",
    "PreparedBuiltinTriangleCallbackProgram",
    "PhysicalSchemaError",
    "ProtocolExecutableIdentity",
    "ProtocolExecutionResult",
    "ProtocolFamily",
    "ProtocolLifecycleError",
    "ProtocolMechanism",
    "ProtocolPhysicalPlan",
    "ProtocolProgramIdentity",
    "PublicCallbackLifecycleError",
    "ResourceBudget",
    "RuntimeEffect",
    "RuntimeRecord",
    "RuntimeStatus",
    "TriangleReductionBatch",
    "TriangleReductionMode",
    "TriangleReductionProtocol",
    "TriangleReductionStaticInput",
    "TriangleWindingPolicy",
    "V4_API_VERSION",
    "V4Target",
    "V4Toolchain",
    "VerifiedCallbackProgram",
    "VerifiedBuiltinTriangleCallbackProgram",
    "VerifiedBuiltinTriangleCallbackSource",
    "VerifiedProtocolProgram",
    "compile_callback_abi",
    "build_builtin_triangle_u32x3_physical_plan",
    "compile_callback_source",
    "compile_builtin_triangle_callback_program",
    "compile_protocol_program",
    "derive_compiler_recognized_any_hit_proof",
    "execute_callback_role",
    "materialize_protocol_program",
    "materialize_builtin_triangle_callback_program",
    "parse_callback_source",
    "standard_protocol_physical_plan",
    "verify_builtin_triangle_callback_source",
    "verify_protocol_contract",
])
